# Generated by Django 5.1.4 on 2024-12-15 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0002_rename_country_name_tr_country_country_name_ru_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='start',
            new_name='hotel_start',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='stars',
            new_name='review_stars',
        ),
    ]
