# Generated by Django 5.1.4 on 2024-12-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0004_remove_hotelphoto_photo_hotelphoto_hotel_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_stars',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, max_length=16),
            preserve_default=False,
        ),
    ]
