# Generated by Django 5.1.4 on 2024-12-19 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0007_alter_hotel_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_stars',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=16),
        ),
    ]
