# Generated by Django 5.1.4 on 2024-12-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0008_alter_review_review_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review_stars',
        ),
        migrations.AddField(
            model_name='review',
            name='stars',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, max_length=16),
            preserve_default=False,
        ),
    ]
