# Generated by Django 5.1.4 on 2024-12-19 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0010_alter_review_stars'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user_name', 'hotel_review')},
        ),
    ]
